specify version of pillow as 10.4.0 due to dependency conflict
ERROR: Cannot install moviepy==2.1.1 and pillow==11.0.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pillow==11.0.0
    moviepy 2.1.1 depends on pillow<11.0 and >=9.2.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict